### ISSUE TITLE
Add entry for ISO 8855:2011 quaternions

### ISSUE THREAD

**Issue by fire** [clemense/quaternion-conventions#4]
Add entry for ISO 8855:2011

**Comment by clemense** [comment]
Sounds good. Any link/reference to this ISO that is not behind a paywall?  I can only find https://www.iso.org/standard/51180.html which is behind a paywall.  And the preview doesn't say anything about quaternions: https://www.iso.org/obp/ui/#iso:std:iso:8855:ed-2:v1:en

**Comment by clemense** [comment]
I went through a copy of ISO 8855:2011 ("Road vehicles — Vehicle dynamics and road-holding ability") and couldn't find any mention of the word "quaternion".  The closest was section "5.2 Angular motion variables" but it only talks about the use of Euler rotations (see Table 1), i.e., roll, pitch, and yaw angle.

I will close this issue, feel free to re-open it, in case I missed something and quaternions are part of the ISO.
